### ISSUE TITLE
clear log on logger creation

### ISSUE THREAD

**Issue by maddinat0r** [maddinat0r/samp-log-core#13]
Adding a way to clear the log on creation would be a nice feature. Probably pass a parameter to `CreateLogger`, check if it's set in `LogManager::RegisterLogger` and clear/delete the log file.

**Comment by maddinat0r** [comment]
Resolved in 5544cb210b255e73a762a4b17003f9c056ff2d19.
Added a config option to clear the log file on startup:
```yaml
Logger:
  plugins/mysql:
    LogLevel: All
    Append: false # clears the log file on logging start instead of appending to it
```
